# This workflow will build and upload a runner jar to keep around for 7 days

name: ci-build

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        cache: maven

    - name: Build
      run: mvn -B package -Dquarkus.package.jar.type=uber-jar --file pom.xml

    - name: Publish Snapshot
      uses: softprops/action-gh-release@v2
      with:
        files: target/*-runner.jar
        make_latest: true
        prerelease: true
        generate_release_notes: false
        tag_name: snapshot-${{ github.sha }}
